server:
  port: 5775
spring:
  datasource:
    username: root
    password: Hsm12138
    url: jdbc:mysql://localhost:3306/facelogin?serverTimezone=GMT%2B8&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver